java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game86.slg.gz -ucs -rating -bank -campaign -adnet > game86.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game87.slg.gz -ucs -rating -bank -campaign -adnet > game87.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game88.slg.gz -ucs -rating -bank -campaign -adnet > game88.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game89.slg.gz -ucs -rating -bank -campaign -adnet > game89.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game94.slg.gz -ucs -rating -bank -campaign -adnet > game94.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game95.slg.gz -ucs -rating -bank -campaign -adnet > game95.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game96.slg.gz -ucs -rating -bank -campaign -adnet > game96.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game99.slg.gz -ucs -rating -bank -campaign -adnet > game99.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game100.slg.gz -ucs -rating -bank -campaign -adnet > game100.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game101.slg.gz -ucs -rating -bank -campaign -adnet > game101.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game102.slg.gz -ucs -rating -bank -campaign -adnet > game102.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game103.slg.gz -ucs -rating -bank -campaign -adnet > game103.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game104.slg.gz -ucs -rating -bank -campaign -adnet > game104.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game110.slg.gz -ucs -rating -bank -campaign -adnet > game110.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game111.slg.gz -ucs -rating -bank -campaign -adnet > game111.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game112.slg.gz -ucs -rating -bank -campaign -adnet > game112.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game113.slg.gz -ucs -rating -bank -campaign -adnet > game113.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game114.slg.gz -ucs -rating -bank -campaign -adnet > game114.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game115.slg.gz -ucs -rating -bank -campaign -adnet > game115.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game116.slg.gz -ucs -rating -bank -campaign -adnet > game116.log
java -cp "lib/*" se.sics.tasim.logtool.Main -handler tau.tac.adx.parser.GeneralHandler -file game117.slg.gz -ucs -rating -bank -campaign -adnet > game117.log
